// eslint.config.mjs
import { defineConfig } from "eslint/config";
import obsidianmd from "eslint-plugin-obsidianmd";

export default defineConfig([
  {
    // main.js is the built bundle (regenerated by esbuild)
    ignores: ["main.js"],
  },
  ...obsidianmd.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["eslint.config.*", "esbuild.config.*"],
        },
      },
      // The dmn-js type interfaces are declared globally in
      // typings/index.d.ts (a global script — see its header comment), so
      // TypeScript knows them but no-undef does not.
      globals: {
        DmnViewer: "readonly",
        DmnView: "readonly",
        DmnChildViewer: "readonly",
        DmnCanvas: "readonly",
        DmnCommandStack: "readonly",
        DmnEventBus: "readonly",
        DmnPopupMenu: "readonly",
        DmnZoomScroll: "readonly",
      },
    },
    rules: {
      "obsidianmd/ui/sentence-case": "off",
      "obsidianmd/no-nodejs-modules": "off",
      // The plugin is named "dmn", so this rule flags every command that
      // contains the word "DMN" — the domain term, not the plugin prefix.
      "obsidianmd/commands/no-plugin-name-in-command-name": "off"
    }
  },
]);
